name: Debug build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - '.github/workflows/clang-format-check.yml'
      - '.github/workflows/publish-release.yml'
      - '.github/workflows/update-deps-list.yml'
    branches:
      - '**'
jobs:
  build:
    uses: ./.github/workflows/build-all-os.yml
    with:
      mode: debug
