name: clang-format Check

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - '.github/workflows/build-debug.yml'
      - '.github/workflows/publish-release.yml'
      - '.github/workflows/update-deps-list.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  clang-format-check:
    name: clang-format Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - './src'
          - './tests'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: clang-format Check
      uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: ${{ matrix.path }}
        clangFormatVersion: 16
